services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: videomatrix
      MYSQL_USER: videomatrix_user
      MYSQL_PASSWORD: videomatrix_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot_password"]
      interval: 1s  
      timeout: 1s  
      retries: 1   

volumes:
  mysql-data: