// <auto-generated />
using BlazorApp3.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorApp3.Migrations
{
    [DbContext(typeof(BlazorApp3Context))]
    [Migration("20240831235153_TranmittersIdForeignKeyNullable")]
    partial class TranmittersIdForeignKeyNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorApp3.Models.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Ip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Device");

                    b.HasDiscriminator().HasValue("Device");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("BlazorApp3.Models.Receiver", b =>
                {
                    b.HasBaseType("BlazorApp3.Models.Device");

                    b.Property<int>("TransmitterId")
                        .HasColumnType("int");

                    b.HasIndex("TransmitterId");

                    b.HasDiscriminator().HasValue("Receiver");
                });

            modelBuilder.Entity("BlazorApp3.Models.Transmitter", b =>
                {
                    b.HasBaseType("BlazorApp3.Models.Device");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Transmitter");
                });

            modelBuilder.Entity("BlazorApp3.Models.Receiver", b =>
                {
                    b.HasOne("BlazorApp3.Models.Transmitter", "Transmitter")
                        .WithMany()
                        .HasForeignKey("TransmitterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Transmitter");
                });
#pragma warning restore 612, 618
        }
    }
}
